default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: GithubProjectManager_development

test:
  <<: *default
  database: GithubProjectManager_test

production:
  <<: *default
  database: GithubProjectManager_production
  username: GithubProjectManager
  password: <%= ENV['GITHUBPROJECTMANAGER_DATABASE_PASSWORD'] %>
